services:
  - type: web
    name: batch-report-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
