services:
  - type: web
    name: batch-report-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app --timeout 300 --workers 2 --worker-class sync --keep-alive 5 --max-requests 1000 --max-requests-jitter 100
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
